### ISSUE TITLE
ICD Elasticsearch DA needs option for enabling public endpoint

### ISSUE THREAD

**Issue by ajainghub** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#224]
When provisioning from the IBM Cloud Catalog, we can enable public and private endpoint of Elasticsearch instance, but this option is not available for selection/configuration on the DA. It enables only the private endpoints when provisioned.

Please add some type of selection/option for enabling public endpoints.

Also need this option for use in the Gen AI RAG DA Stack: https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/204

**Comment by ocofaigh** [comment]
The Elaticsearch `standard` flavor DA is secure by default and complies with fscloud requirements to have no pubic endpoint exposed. If you require public endpoint, then a new `quickstart` variation would be required. If thats the case, you can create an issue for that, but I strongly suggest you try to use private only here. I see no reason why you can not since it will all run inside schematics on VRF enabled accounts
