### ISSUE TITLE
Support using existing ES instance for ES DA

### ISSUE THREAD

**Issue by akocbek** [terraform-ibm-modules/terraform-ibm-icd-elasticsearch#235]
As a user, I do not want to create ES DA in a stack, if ES instance already exists.

**Comment by ocofaigh** [comment]
@akocbek some further info was added in https://github.com/terraform-ibm-modules/terraform-ibm-icd-elasticsearch/issues/238

**Comment by shemau** [comment]
Does this even make sense?

I am interpreting this as a request for `data source` in terraform terms, versus a `resource`.

Of all the resources the DA creates, only access tags (ibm_resource_tag) and keys (ibm_resource_key) might possibly be helpful to extend the existing ES to a new stack.

This could equally apply to any of the persistent storage services (eg. object storage, secrets manager, key manager, cloud database).

I wonder if the RAG stack needs the logic, rather than the ES DA. 

Is the best approach:

- Create `data source` DAs with minimal inputs (variables) and equivalent outputs?
- Force the issue up the stack, making the stack own getting existing information or creating new DA.

I think it is highly undesirable to have a DA that deploys nothing. So thinking out loud, maybe a couple of DAs, one to add access tags to a service and one to add resource keys to a service make sense with a stack that has the flavor to either use existing resources defined somewhere or provision all the required resources.

**Comment by ocofaigh** [comment]
It is needed. For example someone might want to enable the elser module on an existing instance, or create an index on an existing instance. Its also needed for the stack use case where there is no way currently to just ignore a member DA inside a stack

**Comment by kierramarie** [comment]
Currently blocked by this issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5397

**Comment by ocofaigh** [comment]
The provider crash is intermittent so its not a blocker
